extends: 'eslint-config-sinon'

env:
  amd: true
  browser: true
  node: true

globals:
  Set: false

plugins:
  - ie11

rules:
  strict: [error, 'function']

  ie11/no-collection-args: error
  ie11/no-for-in-const: error
  ie11/no-loop-func: warn
  ie11/no-weak-collections: error

overrides:
    files: '*.test.*'
    env:
        mocha: true
    rules:
        strict: [error, 'global']
