language: node_js

sudo: false

node_js:
  # https://github.com/nodejs/LTS
  - "4" # ends April 2018
  - "6" # ends April 2019
  - "8" # ends December 2019

cache:
  directories:
  - node_modules


script:
  - npm test
